
image: node:10-alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - .yarn-cache

stages:
- "Install"
- "Run tests"
- "Deploy new mappings"

Install:
  stage: "Install"
  script:
  - yarn --frozen-lockfile --cache-folder .yarn-cache
  artifacts:
    expire_in: "1 day"
    paths:
    - node_modules

Run tests:
  stage: "Run tests"
  script:
  - yarn test
  after_script:
  - npx codecov

Deploy new mappings:
  stage: "Deploy new mappings"
  only:
    changes:
      - mapping.json
  script:
  - yarn convert-mapping
  - yarn deploy

