dist: xenial
language: generic
git:
  depth: 5

#

jobs:
  include:
    - stage: Test
      if: type = pull_request
      language: node_js
      node_js: 10
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - yarn --frozen-lockfile
      script:
        - yarn test --coverage
      after_script: npx codecov
