const fs = require("fs");
const toml = require("toml");
const fetch = require("node-fetch");
const pick = require("lodash.pick");

// parse rule.toml as traefik REST format
const parseTOML = () => toml.parse(fs.readFileSync("./rules.toml").toString());

// convert rules.toml to simpler JSON mapping
const tomlToMappings = () => {
  const data = parseTOML();
  const services = {};
  Object.keys(data.backends).forEach(key => {
    services[key] = {
      backend: data.backends[key].servers.server0.url
    };
  });
  Object.keys(data.frontends).forEach(key => {
    const frontend = data.frontends[key];
    services[frontend.backend] = {
      ...(services[frontend.backend] || {}),
      rule: frontend.routes.route0.rule,
      // exclude autogenerated keys
      ...pick(frontend, exclude(Object.keys(frontend), ["routes", "backend"]))
    };
  });
  const mappings = Object.keys(services).map(key => ({
    id: key,
    ...services[key]
  }));
  return mappings;
};

const exclude = (keys, exclude) =>
  keys.filter(key => exclude.indexOf(key) === -1);

// convert mappings.json to traefik REST format
const getMappings = () => {
  const mappings = require("./mappings.json");
  const frontends = mappings.reduce(
    (map, entry) => ({
      ...map,
      [entry.id]: {
        backend: entry.id,
        routes: {
          route0: {
            rule: entry.rule
          }
        },
        // apply all keys to frontend, except the 3 shortcuts
        ...pick(entry, exclude(Object.keys(entry), ["backend", "rule", "id"]))
      }
    }),
    {}
  );
  const backends = mappings.reduce(
    (map, entry) => ({
      ...map,
      [entry.id]: {
        servers: {
          server0: {
            url: entry.backend
          }
        }
      }
    }),
    {}
  );
  return {
    frontends,
    backends
  };
};

if (require.main === module) {
  console.log(JSON.stringify(getMappings(), null, 2));
}
